Git Info - ratnakar.settipalli@gmail.com/Hallow58

mysql -u ratnakars -p

create database newMyTracker;

use newMyTracker;

Admin user ratnakars/Xsw@3edc

create table customer_info (customer_id int(25) NOT NULL auto_increment, fname varchar(50) NOT NULL, lname varchar(50) NOT NULL, email varchar(150) NOT NULL, password varchar(50) NOT NULL, status varchar(15), type varchar(25) NOT NULL, PRIMARY KEY (customer_id), UNIQUE KEY customer_id (customer_id), UNIQUE KEY email (email) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

insert into customer_info (fname,lname,email,password,type) values('Ratnakar','Settipalli','ratnakar@gmail.com','Xsw@3edc','1');

--CompanyCode Tables **** Companycode.xml
create table COMPANY_CODE (BUKRS varchar(10) NOT NULL, BUTXT  varchar(50), ORT01 varchar(25), WAERS varchar(10), SPRAS varchar(1), ADRNR varchar(25), ADDRESS1 varchar(50), ADDRESS2 varchar(50), COUNTRY varchar(3), ZIP varchar(10), PHONE varchar(15), FAX varchar(15), PRIMARY KEY (BUKRS)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SHIP_POINT (SHIP_POINT varchar(25) NOT NULL, ADDRESS1 varchar(50), ADDRESS2 varchar(50), CITY varchar(25), COUNTRY varchar(3), ZIP varchar(10), PHONE varchar(15), FAX varchar(15), LANGUAGE varchar(2), BUKRS varchar(10) NOT NULL, PRIMARY KEY (SHIP_POINT),FOREIGN KEY (BUKRS) REFERENCES COMPANY_CODE(BUKRS)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--- Material.xml Tables ****
create table MATERIAL_STORAGE (STO_LOCATION varchar(5) NOT NULL, MAINT_STATUS varchar(3), STOC_IN_QLTY_INS varchar(15), PRIMARY KEY (STO_LOCATION)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table MATERIAL_PLANT (PLANT_CD varchar(10) NOT NULL, MAINT_STATUS varchar(15), MRP_TYPE varchar(3), MRP_CONT varchar(4), STO_LOCATION varchar(5) NOT NULL, PRIMARY KEY (PLANT_CD), FOREIGN KEY (STO_LOCATION) REFERENCES MATERIAL_STORAGE(STO_LOCATION)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table MATERIAL (MATERIAL_CD varchar(25) NOT NULL, MAT_DESC varchar(10), UOM varchar(3), STOCK varchar(2), BOM varchar(2), MAT_TYPE varchar(5), GROSS_WEIGHT varchar(15), NET_WEIGHT varchar(15), MATERIAL_GROUP varchar(5), PLANT_CD varchar(10) NOT NULL, PRIMARY KEY (MATERIAL_CD), FOREIGN KEY (PLANT_CD) REFERENCES MATERIAL_PLANT(PLANT_CD)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--Customer.xml Tables ***
create table CUSTOMER (KUNNR varchar(25) NOT NULL, NAME1 varchar(100), STREET varchar(100), STR_SUPPL3 varchar(100), CITY varchar(25), REGION varchar(3), COUNTRY varchar(3), POSTL_COD1 varchar(10), TELEPHONE varchar(15), FAX varchar(15), PRIMARY KEY (KUNNR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table CUST_BANK (CUST_NUMBER varchar(25) NOT NULL, BANK_COUNTRY varchar(3), BANK_KEY varchar(10), BANK_ACC varchar(12) NOT NULL, BANK_TYPE varchar(5) NOT NULL, PRIMARY KEY (CUST_NUMBER)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Delivery.xml tables ***
create table DELIVERY_HEADER (SOLD_TO_COMPANY_CD varchar(15) NOT NULL, SHIP_TO_COMPANY_CD varchar(15) NOT NULL, DELVI_NBR varchar(15) NOT NULL, ORDER_PLANT_CD varchar(1), ORDER_STATUS_CD varchar(1), CUSTOMER_PO varchar(8), END_USER varchar(50), END_USER_COMPANY_CD varchar(15), OVERRIDE_COMPANY_NAME varchar(50), OVERRIDE_ADDRESS1 varchar(100), OVERRIDE_ADDRESS2 varchar(100), OVERRIDE_CITY varchar(25), OVERRIDE_STATE varchar(3), OVERRIDE_ZIP varchar(10), ORDER_REF_NUM varchar(15) NOT NULL,  PRIMARY KEY (DELVI_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table DELIVERY_OD_HEADER_COMMENT (ORDER_NBR varchar(15) NOT NULL, TYPE varchar(10), LINE varchar(250) NOT NULL,DELVI_NBR_OD_HEADER varchar(15) NOT NULL, PRIMARY KEY (ORDER_NBR,LINE),FOREIGN KEY (DELVI_NBR_OD_HEADER) REFERENCES DELIVERY_HEADER(DELVI_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table DELIVERY_DETAIL (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10) NOT NULL, PRODUCT_NBR varchar(8) NOT NULL, OVERRIDE_PRODUCT varchar(50), ITEM_CAT varchar(5), BASE_UOM varchar(3), NET_VAL varchar(15), ORD_QTY varchar(15), PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table DELIVERY_ITEM_ATTACHMENT (DOKAR varchar(5) NOT NULL, DOKNR varchar(15), DOKVR varchar(5), DOKTL varchar(5), OBJKY varchar(15), ORDER_NBR_OD_DETAIL varchar(15) NOT NULL, ORDER_LINE_NBR_OD_DETAIL varchar(10) NOT NULL,PRIMARY KEY (DOKAR), FOREIGN KEY (ORDER_NBR_OD_DETAIL,ORDER_LINE_NBR_OD_DETAIL) REFERENCES DELIVERY_DETAIL(ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table DELIVERY_OD_DETAIL_COMMENT (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10), TYPE varchar(10), LINE varchar(500), ORDER_NBR_OD_DETAIL varchar(15) NOT NULL, ORDER_LINE_NBR_OD_DETAIL varchar(10) NOT NULL, PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR), FOREIGN KEY (ORDER_NBR_OD_DETAIL,ORDER_LINE_NBR_OD_DETAIL) REFERENCES DELIVERY_DETAIL (ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Invoice.xml Tables ****
create table INV_HEADER (SOLD_FROM_COMPANY_CD varchar(5) NOT NULL,SOLD_TO_COMPANY_CD varchar(15) NOT NULL, SHIP_TO_COMPANY_CD varchar(15) NOT NULL, INVOI_NBR varchar(15) NOT NULL, ORDER_PLANT_CD varchar(1), ORDER_STATUS_CD varchar(1), CUSTOMER_PO varchar(8), END_USER_COMPANY_CD varchar(15), OVERRIDE_COMPANY_NAME varchar(50), OVERRIDE_ADDRESS1 varchar(100), OVERRIDE_ADDRESS2 varchar(100), OVERRIDE_CITY varchar(25), OVERRIDE_STATE varchar(3), OVERRIDE_ZIP varchar(10),  PRIMARY KEY (INVOI_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table INV_HEADER_COMMENT (ORDER_NBR varchar(15) NOT NULL, TYPE varchar(10), LINE varchar(250) NOT NULL, INVOI_NBR_SO_HEADER varchar(15) NOT NULL, PRIMARY KEY (ORDER_NBR,LINE),FOREIGN KEY (INVOI_NBR_SO_HEADER) REFERENCES INV_HEADER(INVOI_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table INV_DETAIL (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10) NOT NULL, PRODUCT_NBR varchar(8) NOT NULL, OVERRIDE_PRODUCT varchar(50), ITEM_CAT varchar(5), BASE_UOM varchar(3), NET_VAL varchar(15),  PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table INV_ITEM_ATTACHMENT (DOKAR varchar(5) NOT NULL, DOKNR varchar(15), DOKVR varchar(5), DOKTL varchar(5), OBJKY varchar(15), INVOI_NUM_SO varchar(15) NOT NULL, INVOI_ORD_NUM varchar(10) NOT NULL, PRIMARY KEY (DOKAR), FOREIGN KEY (INVOI_NUM_SO, INVOI_ORD_NUM) REFERENCES INV_DETAIL(ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table INV_DETAIL_COMMENT (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10), TYPE varchar(10), LINE varchar(500), ORDER_NBR_SO_DETAIL varchar(15) NOT NULL, ORDER_LINE_NBR_SO_DETAIL varchar(10) NOT NULL,PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR),FOREIGN KEY (ORDER_NBR_SO_DETAIL, ORDER_LINE_NBR_SO_DETAIL) REFERENCES INV_DETAIL (ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- sales.xml Tables ****
create table SO_HEADER (ORDER_TYPE varchar(3) NOT NULL, SOLD_FROM_COMPANY_CD varchar(5) NOT NULL,SOLD_TO_COMPANY_CD varchar(15) NOT NULL, SHIP_TO_COMPANY_CD varchar(15) NOT NULL, ORDER_NBR varchar(15) NOT NULL, ORDER_NBR_VER varchar(15), ORDER_PLANT_CD varchar(1), ORDER_STATUS_CD varchar(1), CUSTOMER_PO varchar(25), END_USER varchar(50), END_USER_COMPANY_CD varchar(15), OVERRIDE_COMPANY_NAME varchar(50), OVERRIDE_ADDRESS1 varchar(100), OVERRIDE_ADDRESS2 varchar(100), OVERRIDE_CITY varchar(25), OVERRIDE_STATE varchar(3), OVERRIDE_ZIP varchar(10), PRIMARY KEY (ORDER_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SO_HEADER_COMMENT (ORDER_NBR varchar(15) NOT NULL, TYPE varchar(10), LINE varchar(250) NOT NULL, ORDER_NBR_SO_HEADER varchar(15) NOT NULL, PRIMARY KEY (ORDER_NBR,LINE), FOREIGN KEY (ORDER_NBR_SO_HEADER) REFERENCES SO_HEADER(ORDER_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SO_DETAIL (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10) NOT NULL, PRODUCT_NBR varchar(8) NOT NULL, OVERRIDE_PRODUCT varchar(50), ITEM_CAT varchar(5), BASE_UOM varchar(3), NET_VAL varchar(15), ORD_QTY varchar(15), PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SO_DETAIL_COMMENT (ORDER_NBR varchar(15) NOT NULL, ORDER_LINE_NBR varchar(10) NOT NULL, TYPE varchar(10), LINE varchar(500), ORDER_NBR_SO_DETAIL varchar(15) NOT NULL, ORDER_LINE_NBR_SO_DETAIL varchar(10) NOT NULL, PRIMARY KEY (ORDER_NBR,ORDER_LINE_NBR),FOREIGN KEY (ORDER_NBR_SO_DETAIL, ORDER_LINE_NBR_SO_DETAIL) REFERENCES SO_DETAIL(ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table SO_ITEM_ATTACHMENT (DOKAR varchar(5) NOT NULL, DOKNR varchar(15), DOKVR varchar(5), DOKTL varchar(5), OBJKY varchar(15), ORDER_NBR_SO_DETAIL varchar(15) NOT NULL, ORDER_LINE_NBR_SO_DETAIL varchar(10) NOT NULL, PRIMARY KEY (DOKAR), FOREIGN KEY (ORDER_NBR_SO_DETAIL,ORDER_LINE_NBR_SO_DETAIL) REFERENCES SO_DETAIL(ORDER_NBR,ORDER_LINE_NBR)) ENGINE=InnoDB DEFAULT CHARSET=utf8;






